"""Fail-closed authorization policy for Basecamp capabilities."""

from __future__ import annotations

import hashlib
import json
import time
from collections.abc import Mapping
from dataclasses import dataclass
from enum import StrEnum
from typing import Any


class PolicyDeniedError(PermissionError):
    """An operation is known but is not authorized in this context."""


class UnknownCapabilityError(PolicyDeniedError):
    """An unregistered operation was requested."""


class RiskClass(StrEnum):
    READ = "read"
    ORDINARY_WRITE = "ordinary_write"
    SENSITIVE_WRITE = "sensitive_write"
    ADMINLAND_DENIED = "adminland_denied"


class TriggerClass(StrEnum):
    DIRECT_MENTION = "direct_mention"
    ASSIGNMENT = "assignment"
    APPROVED_SCHEDULE = "approved_schedule"
    MANUAL = "manual"
    UNATTENDED = "unattended"


@dataclass(frozen=True)
class Capability:
    name: str
    domain: str
    service: str
    method: str
    risk: RiskClass
    project_argument: str | None = None
    owner_service: str | None = None
    owner_method: str | None = None
    owner_argument: str | None = None
    owner_parameter: str | None = None
    result_id_field: str = "id"
    context_arguments: tuple[str, ...] = ()


@dataclass(frozen=True)
class ExecutionContext:
    trigger: TriggerClass
    project_id: str
    profile_id: str


def action_digest(capability: str, project_id: str, arguments: Mapping[str, Any]) -> str:
    payload = json.dumps(
        {"capability": capability, "project_id": project_id, "arguments": arguments},
        sort_keys=True,
        separators=(",", ":"),
        default=str,
    )
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


@dataclass(frozen=True)
class ActionApproval:
    capability: str
    project_id: str
    arguments_digest: str
    approved_by: str
    expires_at: float

    def permits(self, capability: str, project_id: str, arguments: Mapping[str, Any]) -> bool:
        return (
            bool(self.approved_by)
            and time.time() <= self.expires_at
            and self.capability == capability
            and self.project_id == project_id
            and self.arguments_digest == action_digest(capability, project_id, arguments)
        )


class CapabilityRegistry:
    def __init__(self, capabilities: tuple[Capability, ...] = ()) -> None:
        self._items = {item.name: item for item in capabilities}

    def register(self, capability: Capability) -> None:
        if capability.name in self._items:
            raise ValueError(f"Duplicate Basecamp capability: {capability.name}")
        self._items[capability.name] = capability

    def get(self, name: str) -> Capability:
        try:
            return self._items[name]
        except KeyError as exc:
            raise UnknownCapabilityError(f"Unknown Basecamp capability: {name}") from exc

    def list(self) -> tuple[Capability, ...]:
        return tuple(sorted(self._items.values(), key=lambda item: item.name))


class PolicyEngine:
    def __init__(self, registry: CapabilityRegistry) -> None:
        self.registry = registry

    def authorize(
        self,
        name: str,
        arguments: Mapping[str, Any],
        context: ExecutionContext,
        approval: ActionApproval | None = None,
    ) -> Capability:
        capability = self.registry.get(name)
        if capability.risk is RiskClass.ADMINLAND_DENIED:
            raise PolicyDeniedError(f"{name} is an Adminland-only operation")
        if capability.risk is RiskClass.READ:
            return capability
        if requires_action_approval(capability, arguments):
            if approval is None or not approval.permits(name, context.project_id, arguments):
                raise PolicyDeniedError(f"{name} requires an unexpired action-time approval for these exact arguments")
            return capability
        if capability.risk is RiskClass.ORDINARY_WRITE:
            allowed = {
                TriggerClass.DIRECT_MENTION,
                TriggerClass.ASSIGNMENT,
                TriggerClass.APPROVED_SCHEDULE,
            }
            if context.trigger not in allowed:
                raise PolicyDeniedError(f"{name} requires a direct mention, assignment, or approved schedule")
            return capability
        raise PolicyDeniedError(f"Unsupported Basecamp risk class for {name}")


def requires_action_approval(capability: Capability, arguments: Mapping[str, Any]) -> bool:
    if capability.risk is RiskClass.SENSITIVE_WRITE:
        return True
    sensitive_fields = {
        "admissions",
        "assignee_ids",
        "completion_subscriber_ids",
        "create",
        "grant",
        "participant_ids",
        "paused",
        "person_id",
        "revoke",
        "schedule",
        "schedule_attributes",
        "subscriptions",
        "unsubscriptions",
        "visible_to_clients",
    }
    if any(key in arguments and arguments[key] is not None for key in sensitive_fields):
        return True
    notify = arguments.get("notify")
    return notify is not None and notify is not False


def default_registry() -> CapabilityRegistry:
    """Return the reviewed Basecamp 0.16 member-capability inventory."""

    read = RiskClass.READ
    write = RiskClass.ORDINARY_WRITE
    sensitive = RiskClass.SENSITIVE_WRITE
    denied = RiskClass.ADMINLAND_DENIED
    definitions = (
        # Projects and people.
        Capability("projects.list", "projects", "projects", "list", read),
        Capability("projects.recent", "projects", "projects", "list_recent_projects", read),
        Capability("projects.get", "projects", "projects", "get", read, "project_id"),
        Capability("projects.update", "projects", "projects", "update", write, "project_id"),
        Capability("projects.archive", "projects", "projects", "archive", sensitive, "project_id"),
        Capability("projects.restore", "projects", "projects", "unarchive", sensitive, "project_id"),
        Capability("projects.trash", "projects", "projects", "trash", sensitive, "project_id"),
        Capability("people.list", "people", "people", "list_for_project", read, "project_id"),
        Capability("people.get", "people", "people", "get", read),
        Capability("people.project_access", "people", "people", "update_project_access", sensitive, "project_id"),
        Capability("people.invite", "people", "people", "update_project_access", denied, "project_id"),
        # Todos, messages, comments, Campfire, cards, schedules, and check-ins.
        Capability(
            "todos.list",
            "todos",
            "todos",
            "list",
            read,
            owner_service="todolists",
            owner_method="get",
            owner_argument="todolist_id",
            owner_parameter="id",
        ),
        Capability(
            "todos.get",
            "todos",
            "todos",
            "get",
            read,
            owner_service="todos",
            owner_method="get",
            owner_argument="todo_id",
        ),
        Capability(
            "todos.create",
            "todos",
            "todos",
            "create",
            write,
            owner_service="todolists",
            owner_method="get",
            owner_argument="todolist_id",
            owner_parameter="id",
        ),
        Capability(
            "todos.create_loose",
            "todos",
            "todos",
            "create_todoset_todo",
            write,
            "bucket_id",
            owner_service="todosets",
            owner_method="get",
            owner_argument="todoset_id",
        ),
        Capability(
            "todos.update",
            "todos",
            "todos",
            "update",
            write,
            owner_service="todos",
            owner_method="get",
            owner_argument="todo_id",
        ),
        Capability(
            "todos.reposition",
            "todos",
            "todos",
            "reposition",
            write,
            owner_service="todos",
            owner_method="get",
            owner_argument="todo_id",
        ),
        Capability(
            "todos.complete",
            "todos",
            "todos",
            "complete",
            write,
            owner_service="todos",
            owner_method="get",
            owner_argument="todo_id",
        ),
        Capability(
            "todos.restore",
            "todos",
            "todos",
            "uncomplete",
            write,
            owner_service="todos",
            owner_method="get",
            owner_argument="todo_id",
        ),
        Capability(
            "messages.list",
            "messages",
            "messages",
            "list",
            read,
            owner_service="message_boards",
            owner_method="get",
            owner_argument="board_id",
        ),
        Capability(
            "messages.get",
            "messages",
            "messages",
            "get",
            read,
            owner_service="messages",
            owner_method="get",
            owner_argument="message_id",
        ),
        Capability(
            "messages.create",
            "messages",
            "messages",
            "create",
            write,
            owner_service="message_boards",
            owner_method="get",
            owner_argument="board_id",
        ),
        Capability(
            "messages.update",
            "messages",
            "messages",
            "update",
            write,
            owner_service="messages",
            owner_method="get",
            owner_argument="message_id",
        ),
        Capability(
            "messages.pin",
            "messages",
            "messages",
            "pin",
            write,
            owner_service="messages",
            owner_method="get",
            owner_argument="message_id",
        ),
        Capability(
            "messages.unpin",
            "messages",
            "messages",
            "unpin",
            write,
            owner_service="messages",
            owner_method="get",
            owner_argument="message_id",
        ),
        Capability(
            "comments.list",
            "comments",
            "comments",
            "list",
            read,
            owner_service="events",
            owner_method="list",
            owner_argument="recording_id",
        ),
        Capability(
            "comments.create",
            "comments",
            "comments",
            "create",
            write,
            owner_service="events",
            owner_method="list",
            owner_argument="recording_id",
        ),
        Capability(
            "comments.update",
            "comments",
            "comments",
            "update",
            write,
            owner_service="comments",
            owner_method="get",
            owner_argument="comment_id",
        ),
        Capability(
            "comments.get",
            "comments",
            "comments",
            "get",
            read,
            owner_service="comments",
            owner_method="get",
            owner_argument="comment_id",
        ),
        Capability(
            "message_boards.get",
            "messages",
            "message_boards",
            "get",
            read,
            owner_service="message_boards",
            owner_method="get",
            owner_argument="board_id",
        ),
        Capability("message_types.create", "messages", "message_types", "create", sensitive, "bucket_id"),
        Capability("message_types.get", "messages", "message_types", "get", read, "bucket_id"),
        Capability("message_types.update", "messages", "message_types", "update", sensitive, "bucket_id"),
        Capability("message_types.delete", "messages", "message_types", "delete", sensitive, "bucket_id"),
        Capability(
            "campfire.get",
            "campfire",
            "campfires",
            "get",
            read,
            owner_service="campfires",
            owner_method="get",
            owner_argument="campfire_id",
        ),
        Capability("campfire.list", "campfire", "campfires", "list", read),
        Capability(
            "campfire.line.get",
            "campfire",
            "campfires",
            "get_line",
            read,
            owner_service="campfires",
            owner_method="get",
            owner_argument="campfire_id",
        ),
        Capability(
            "campfire.history",
            "campfire",
            "campfires",
            "list_lines",
            read,
            owner_service="campfires",
            owner_method="get",
            owner_argument="campfire_id",
        ),
        Capability(
            "campfire.uploads",
            "campfire",
            "campfires",
            "list_uploads",
            read,
            owner_service="campfires",
            owner_method="get",
            owner_argument="campfire_id",
        ),
        Capability(
            "campfire.post",
            "campfire",
            "campfires",
            "create_line",
            write,
            owner_service="campfires",
            owner_method="get",
            owner_argument="campfire_id",
        ),
        Capability(
            "campfire.update",
            "campfire",
            "campfires",
            "update_line",
            write,
            owner_service="campfires",
            owner_method="get",
            owner_argument="campfire_id",
        ),
        Capability(
            "campfire.delete",
            "campfire",
            "campfires",
            "delete_line",
            sensitive,
            owner_service="campfires",
            owner_method="get",
            owner_argument="campfire_id",
        ),
        Capability(
            "cards.list",
            "cards",
            "cards",
            "list",
            read,
            owner_service="card_columns",
            owner_method="get",
            owner_argument="column_id",
        ),
        Capability(
            "cards.get",
            "cards",
            "cards",
            "get",
            read,
            owner_service="cards",
            owner_method="get",
            owner_argument="card_id",
        ),
        Capability(
            "cards.create",
            "cards",
            "cards",
            "create",
            write,
            owner_service="card_columns",
            owner_method="get",
            owner_argument="column_id",
        ),
        Capability(
            "cards.update",
            "cards",
            "cards",
            "update_verbatim",
            write,
            owner_service="cards",
            owner_method="get",
            owner_argument="card_id",
        ),
        Capability(
            "cards.move",
            "cards",
            "cards",
            "move",
            sensitive,
            owner_service="cards",
            owner_method="get",
            owner_argument="card_id",
        ),
        Capability(
            "cards.steps.get",
            "cards",
            "card_steps",
            "get",
            read,
            owner_service="card_steps",
            owner_method="get",
            owner_argument="step_id",
        ),
        Capability(
            "cards.steps.create",
            "cards",
            "card_steps",
            "create",
            write,
            owner_service="cards",
            owner_method="get",
            owner_argument="card_id",
        ),
        Capability(
            "cards.steps.update",
            "cards",
            "card_steps",
            "update",
            write,
            owner_service="card_steps",
            owner_method="get",
            owner_argument="step_id",
        ),
        Capability(
            "cards.steps.complete",
            "cards",
            "card_steps",
            "set_completion",
            write,
            owner_service="card_steps",
            owner_method="get",
            owner_argument="step_id",
        ),
        Capability(
            "cards.steps.reposition",
            "cards",
            "card_steps",
            "reposition",
            write,
            owner_service="cards",
            owner_method="get",
            owner_argument="card_id",
        ),
        Capability(
            "card_tables.get",
            "cards",
            "card_tables",
            "get",
            read,
            owner_service="card_tables",
            owner_method="get",
            owner_argument="card_table_id",
        ),
        Capability(
            "card_columns.get",
            "cards",
            "card_columns",
            "get",
            read,
            owner_service="card_columns",
            owner_method="get",
            owner_argument="column_id",
        ),
        Capability(
            "card_columns.create",
            "cards",
            "card_columns",
            "create",
            sensitive,
            owner_service="card_tables",
            owner_method="get",
            owner_argument="card_table_id",
        ),
        Capability(
            "card_columns.update",
            "cards",
            "card_columns",
            "update",
            sensitive,
            owner_service="card_columns",
            owner_method="get",
            owner_argument="column_id",
        ),
        Capability(
            "card_columns.move",
            "cards",
            "card_columns",
            "move",
            sensitive,
            owner_service="card_tables",
            owner_method="get",
            owner_argument="card_table_id",
        ),
        Capability(
            "card_columns.color",
            "cards",
            "card_columns",
            "set_color",
            sensitive,
            "bucket_id",
            owner_service="card_columns",
            owner_method="get",
            owner_argument="column_id",
        ),
        Capability(
            "card_columns.hold.enable",
            "cards",
            "card_columns",
            "enable_on_hold",
            sensitive,
            "bucket_id",
            owner_service="card_columns",
            owner_method="get",
            owner_argument="column_id",
        ),
        Capability(
            "card_columns.hold.disable",
            "cards",
            "card_columns",
            "disable_on_hold",
            sensitive,
            "bucket_id",
            owner_service="card_columns",
            owner_method="get",
            owner_argument="column_id",
        ),
        Capability(
            "card_columns.subscribe",
            "cards",
            "card_columns",
            "subscribe_to_column",
            write,
            owner_service="card_columns",
            owner_method="get",
            owner_argument="column_id",
        ),
        Capability(
            "card_columns.unsubscribe",
            "cards",
            "card_columns",
            "unsubscribe_from_column",
            write,
            owner_service="card_columns",
            owner_method="get",
            owner_argument="column_id",
        ),
        Capability(
            "wormholes.create",
            "cards",
            "wormholes",
            "create",
            sensitive,
            "bucket_id",
            owner_service="card_tables",
            owner_method="get",
            owner_argument="card_table_id",
        ),
        Capability(
            "wormholes.update",
            "cards",
            "wormholes",
            "update",
            sensitive,
            "bucket_id",
            context_arguments=("card_table_id",),
        ),
        Capability(
            "wormholes.delete",
            "cards",
            "wormholes",
            "delete",
            sensitive,
            "bucket_id",
            context_arguments=("card_table_id",),
        ),
        Capability(
            "schedules.container.get",
            "schedules",
            "schedules",
            "get",
            read,
            owner_service="schedules",
            owner_method="get",
            owner_argument="schedule_id",
        ),
        Capability(
            "schedules.list",
            "schedules",
            "schedules",
            "list_entries",
            read,
            owner_service="schedules",
            owner_method="get",
            owner_argument="schedule_id",
        ),
        Capability(
            "schedules.get",
            "schedules",
            "schedules",
            "get_entry",
            read,
            owner_service="schedules",
            owner_method="get_entry",
            owner_argument="entry_id",
        ),
        Capability(
            "schedules.create",
            "schedules",
            "schedules",
            "create_entry",
            write,
            owner_service="schedules",
            owner_method="get",
            owner_argument="schedule_id",
        ),
        Capability(
            "schedules.update",
            "schedules",
            "schedules",
            "update_entry",
            write,
            owner_service="schedules",
            owner_method="get_entry",
            owner_argument="entry_id",
        ),
        Capability(
            "schedules.occurrence",
            "schedules",
            "schedules",
            "get_entry_occurrence",
            read,
            owner_service="schedules",
            owner_method="get_entry",
            owner_argument="entry_id",
        ),
        Capability(
            "schedules.settings",
            "schedules",
            "schedules",
            "update_settings",
            sensitive,
            owner_service="schedules",
            owner_method="get",
            owner_argument="schedule_id",
        ),
        Capability(
            "calendars.get",
            "schedules",
            "calendars",
            "get_calendar",
            read,
            owner_service="calendars",
            owner_method="get_calendar",
            owner_argument="calendar_id",
        ),
        Capability(
            "calendars.update",
            "schedules",
            "calendars",
            "update_calendar",
            sensitive,
            owner_service="calendars",
            owner_method="get_calendar",
            owner_argument="calendar_id",
        ),
        Capability(
            "events.list",
            "schedules",
            "events",
            "list",
            read,
            owner_service="events",
            owner_method="list",
            owner_argument="recording_id",
        ),
        Capability(
            "checkins.questions",
            "checkins",
            "checkins",
            "list_questions",
            read,
            owner_service="checkins",
            owner_method="get_questionnaire",
            owner_argument="questionnaire_id",
        ),
        Capability(
            "checkins.answers",
            "checkins",
            "checkins",
            "list_answers",
            read,
            owner_service="checkins",
            owner_method="get_question",
            owner_argument="question_id",
        ),
        Capability(
            "checkins.answer",
            "checkins",
            "checkins",
            "create_answer",
            write,
            owner_service="checkins",
            owner_method="get_question",
            owner_argument="question_id",
        ),
        Capability(
            "checkins.answer.update",
            "checkins",
            "checkins",
            "update_answer",
            write,
            owner_service="checkins",
            owner_method="get_answer",
            owner_argument="answer_id",
        ),
        Capability(
            "checkins.question.update",
            "checkins",
            "checkins",
            "update_question",
            write,
            owner_service="checkins",
            owner_method="get_question",
            owner_argument="question_id",
        ),
        Capability(
            "checkins.pause",
            "checkins",
            "checkins",
            "pause",
            sensitive,
            owner_service="checkins",
            owner_method="get_question",
            owner_argument="question_id",
        ),
        Capability(
            "checkins.resume",
            "checkins",
            "checkins",
            "resume",
            sensitive,
            owner_service="checkins",
            owner_method="get_question",
            owner_argument="question_id",
        ),
        Capability(
            "checkins.questionnaire.get",
            "checkins",
            "checkins",
            "get_questionnaire",
            read,
            owner_service="checkins",
            owner_method="get_questionnaire",
            owner_argument="questionnaire_id",
        ),
        Capability(
            "checkins.question.get",
            "checkins",
            "checkins",
            "get_question",
            read,
            owner_service="checkins",
            owner_method="get_question",
            owner_argument="question_id",
        ),
        Capability(
            "checkins.answer.get",
            "checkins",
            "checkins",
            "get_answer",
            read,
            owner_service="checkins",
            owner_method="get_answer",
            owner_argument="answer_id",
        ),
        Capability(
            "checkins.answerers",
            "checkins",
            "checkins",
            "answerers",
            read,
            owner_service="checkins",
            owner_method="get_question",
            owner_argument="question_id",
        ),
        Capability(
            "checkins.answers.by_person",
            "checkins",
            "checkins",
            "by_person",
            read,
            owner_service="checkins",
            owner_method="get_question",
            owner_argument="question_id",
        ),
        Capability(
            "checkins.question.create",
            "checkins",
            "checkins",
            "create_question",
            write,
            owner_service="checkins",
            owner_method="get_questionnaire",
            owner_argument="questionnaire_id",
        ),
        # Documents and files.
        Capability(
            "documents.list",
            "files",
            "documents",
            "list",
            read,
            owner_service="vaults",
            owner_method="get",
            owner_argument="vault_id",
        ),
        Capability(
            "documents.get",
            "files",
            "documents",
            "get",
            read,
            owner_service="documents",
            owner_method="get",
            owner_argument="document_id",
        ),
        Capability(
            "documents.create",
            "files",
            "documents",
            "create",
            write,
            owner_service="vaults",
            owner_method="get",
            owner_argument="vault_id",
        ),
        Capability(
            "documents.update",
            "files",
            "documents",
            "update",
            write,
            owner_service="documents",
            owner_method="get",
            owner_argument="document_id",
        ),
        Capability(
            "uploads.list",
            "files",
            "uploads",
            "list",
            read,
            owner_service="vaults",
            owner_method="get",
            owner_argument="vault_id",
        ),
        Capability(
            "uploads.get",
            "files",
            "uploads",
            "get",
            read,
            owner_service="uploads",
            owner_method="get",
            owner_argument="upload_id",
        ),
        Capability(
            "uploads.create",
            "files",
            "uploads",
            "create",
            write,
            owner_service="vaults",
            owner_method="get",
            owner_argument="vault_id",
        ),
        Capability(
            "uploads.version",
            "files",
            "uploads",
            "create_version",
            write,
            owner_service="uploads",
            owner_method="get",
            owner_argument="upload_id",
        ),
        Capability(
            "uploads.update",
            "files",
            "uploads",
            "update",
            write,
            owner_service="uploads",
            owner_method="get",
            owner_argument="upload_id",
        ),
        Capability(
            "uploads.versions",
            "files",
            "uploads",
            "list_versions",
            read,
            owner_service="uploads",
            owner_method="get",
            owner_argument="upload_id",
        ),
        Capability(
            "vaults.get",
            "files",
            "vaults",
            "get",
            read,
            owner_service="vaults",
            owner_method="get",
            owner_argument="vault_id",
        ),
        Capability(
            "vaults.list",
            "files",
            "vaults",
            "list",
            read,
            owner_service="vaults",
            owner_method="get",
            owner_argument="vault_id",
        ),
        Capability(
            "vaults.create",
            "files",
            "vaults",
            "create",
            sensitive,
            owner_service="vaults",
            owner_method="get",
            owner_argument="vault_id",
        ),
        Capability(
            "vaults.update",
            "files",
            "vaults",
            "update",
            sensitive,
            owner_service="vaults",
            owner_method="get",
            owner_argument="vault_id",
        ),
        Capability(
            "cloud_files.get",
            "files",
            "cloud_files",
            "get_cloud_file",
            read,
            owner_service="cloud_files",
            owner_method="get_cloud_file",
            owner_argument="cloud_file_id",
        ),
        Capability(
            "cloud_files.create",
            "files",
            "cloud_files",
            "create_cloud_file",
            write,
            "bucket_id",
            owner_service="vaults",
            owner_method="get",
            owner_argument="vault_id",
        ),
        Capability(
            "cloud_files.update",
            "files",
            "cloud_files",
            "update_cloud_file",
            write,
            owner_service="cloud_files",
            owner_method="get_cloud_file",
            owner_argument="cloud_file_id",
        ),
        Capability(
            "google_documents.get",
            "files",
            "google_documents",
            "get_google_document",
            read,
            owner_service="google_documents",
            owner_method="get_google_document",
            owner_argument="google_document_id",
        ),
        Capability(
            "google_documents.create",
            "files",
            "google_documents",
            "create_google_document",
            write,
            "bucket_id",
            owner_service="vaults",
            owner_method="get",
            owner_argument="vault_id",
        ),
        Capability(
            "google_documents.update",
            "files",
            "google_documents",
            "update_google_document",
            write,
            owner_service="google_documents",
            owner_method="get_google_document",
            owner_argument="google_document_id",
        ),
        Capability("folders.list", "files", "folders", "list_folders", read),
        Capability("folders.get", "files", "folders", "get_folder", read),
        Capability("folders.create", "files", "folders", "create_folder", sensitive),
        Capability("folders.update", "files", "folders", "update_folder", sensitive),
        Capability("folders.delete", "files", "folders", "delete_folder", sensitive),
        # Discovery and reporting.
        Capability("search.query", "search", "search", "search", read),
        Capability("reports.progress", "reports", "reports", "progress", read),
        Capability("reports.assigned", "reports", "reports", "assigned", read),
        Capability("reports.overdue", "reports", "reports", "overdue", read),
        Capability("reports.person_progress", "reports", "reports", "person_progress", read),
        Capability("reports.upcoming", "reports", "reports", "upcoming", read),
        Capability("search.metadata", "search", "search", "metadata", read),
        Capability("activity.timeline", "activity", "timeline", "get_project_timeline", read, "project_id"),
        Capability("timesheets.project", "timesheets", "timesheets", "for_project", read, "project_id"),
        Capability(
            "timesheets.recording",
            "timesheets",
            "timesheets",
            "for_recording",
            read,
            owner_service="events",
            owner_method="list",
            owner_argument="recording_id",
        ),
        Capability(
            "timesheets.create",
            "timesheets",
            "timesheets",
            "create",
            write,
            owner_service="events",
            owner_method="list",
            owner_argument="recording_id",
        ),
        Capability(
            "timesheets.update",
            "timesheets",
            "timesheets",
            "update",
            write,
            owner_service="timesheets",
            owner_method="get",
            owner_argument="entry_id",
        ),
        Capability(
            "timesheets.delete",
            "timesheets",
            "timesheets",
            "destroy",
            sensitive,
            owner_service="timesheets",
            owner_method="get",
            owner_argument="entry_id",
        ),
        Capability(
            "timesheets.get",
            "timesheets",
            "timesheets",
            "get",
            read,
            owner_service="timesheets",
            owner_method="get",
            owner_argument="entry_id",
        ),
        Capability("timesheets.report", "timesheets", "timesheets", "report", read),
        Capability(
            "forwards.inbox.get",
            "extras",
            "forwards",
            "get_inbox",
            read,
            owner_service="forwards",
            owner_method="get_inbox",
            owner_argument="inbox_id",
        ),
        Capability(
            "forwards.list",
            "extras",
            "forwards",
            "list",
            read,
            owner_service="forwards",
            owner_method="get_inbox",
            owner_argument="inbox_id",
        ),
        Capability(
            "forwards.get",
            "extras",
            "forwards",
            "get",
            read,
            owner_service="forwards",
            owner_method="get",
            owner_argument="forward_id",
        ),
        Capability(
            "forwards.replies",
            "extras",
            "forwards",
            "list_replies",
            read,
            owner_service="forwards",
            owner_method="get",
            owner_argument="forward_id",
        ),
        Capability(
            "forwards.reply.get",
            "extras",
            "forwards",
            "get_reply",
            read,
            owner_service="forwards",
            owner_method="get",
            owner_argument="forward_id",
        ),
        # Personal collaboration affordances.
        Capability(
            "subscriptions.get",
            "extras",
            "subscriptions",
            "get",
            read,
            owner_service="events",
            owner_method="list",
            owner_argument="recording_id",
        ),
        Capability(
            "subscriptions.subscribe",
            "extras",
            "subscriptions",
            "subscribe",
            write,
            owner_service="events",
            owner_method="list",
            owner_argument="recording_id",
        ),
        Capability(
            "subscriptions.unsubscribe",
            "extras",
            "subscriptions",
            "unsubscribe",
            write,
            owner_service="events",
            owner_method="list",
            owner_argument="recording_id",
        ),
        Capability(
            "subscriptions.update",
            "extras",
            "subscriptions",
            "update",
            write,
            owner_service="events",
            owner_method="list",
            owner_argument="recording_id",
        ),
        Capability("bookmarks.list", "extras", "bookmarks", "list_my_bookmarks", read),
        Capability(
            "bookmarks.create",
            "extras",
            "bookmarks",
            "create_bookmark",
            write,
            owner_service="events",
            owner_method="list",
            owner_argument="recording_id",
        ),
        Capability(
            "bookmarks.get",
            "extras",
            "bookmarks",
            "get_bookmark",
            read,
            owner_service="events",
            owner_method="list",
            owner_argument="recording_id",
        ),
        Capability(
            "bookmarks.delete",
            "extras",
            "bookmarks",
            "delete_bookmark",
            sensitive,
            owner_service="events",
            owner_method="list",
            owner_argument="recording_id",
        ),
        Capability(
            "boosts.create",
            "extras",
            "boosts",
            "create_recording_boost",
            write,
            owner_service="events",
            owner_method="list",
            owner_argument="recording_id",
        ),
        Capability(
            "boosts.list",
            "extras",
            "boosts",
            "list_recording_boosts",
            read,
            owner_service="events",
            owner_method="list",
            owner_argument="recording_id",
        ),
        Capability(
            "boosts.delete",
            "extras",
            "boosts",
            "delete_boost",
            sensitive,
            owner_service="boosts",
            owner_method="get_boost",
            owner_argument="boost_id",
        ),
        Capability(
            "boosts.get",
            "extras",
            "boosts",
            "get_boost",
            read,
            owner_service="boosts",
            owner_method="get_boost",
            owner_argument="boost_id",
        ),
        Capability(
            "boosts.event.create",
            "extras",
            "boosts",
            "create_event_boost",
            write,
            owner_service="events",
            owner_method="list",
            owner_argument="recording_id",
        ),
        Capability(
            "boosts.event.list",
            "extras",
            "boosts",
            "list_event_boosts",
            read,
            owner_service="events",
            owner_method="list",
            owner_argument="recording_id",
        ),
        Capability("gauges.list", "extras", "gauges", "list_gauge_needles", read, "project_id"),
        Capability(
            "gauges.update",
            "extras",
            "gauges",
            "update_gauge_needle",
            write,
            owner_service="gauges",
            owner_method="get_gauge_needle",
            owner_argument="needle_id",
        ),
        Capability("gauges.create", "extras", "gauges", "create_gauge_needle", write, "project_id"),
        Capability(
            "gauges.delete",
            "extras",
            "gauges",
            "destroy_gauge_needle",
            sensitive,
            owner_service="gauges",
            owner_method="get_gauge_needle",
            owner_argument="needle_id",
        ),
        Capability("gauges.toggle", "extras", "gauges", "toggle_gauge", sensitive, "project_id"),
        Capability(
            "gauges.get",
            "extras",
            "gauges",
            "get_gauge_needle",
            read,
            owner_service="gauges",
            owner_method="get_gauge_needle",
            owner_argument="needle_id",
        ),
        Capability("gauges.summary", "extras", "gauges", "list_gauges", read, "bucket_ids"),
        Capability(
            "hillcharts.get",
            "extras",
            "hill_charts",
            "get",
            read,
            owner_service="todosets",
            owner_method="get",
            owner_argument="todoset_id",
        ),
        Capability(
            "hillcharts.update",
            "extras",
            "hill_charts",
            "update_settings",
            write,
            owner_service="todosets",
            owner_method="get",
            owner_argument="todoset_id",
        ),
        Capability(
            "recordings.archive",
            "recordings",
            "recordings",
            "archive",
            sensitive,
            owner_service="events",
            owner_method="list",
            owner_argument="recording_id",
        ),
        Capability(
            "recordings.restore",
            "recordings",
            "recordings",
            "unarchive",
            sensitive,
            owner_service="events",
            owner_method="list",
            owner_argument="recording_id",
        ),
        Capability(
            "recordings.trash",
            "recordings",
            "recordings",
            "trash",
            sensitive,
            owner_service="events",
            owner_method="list",
            owner_argument="recording_id",
        ),
        Capability(
            "recordings.spotlight",
            "recordings",
            "recordings",
            "spotlight",
            sensitive,
            owner_service="events",
            owner_method="list",
            owner_argument="recording_id",
        ),
        Capability(
            "recordings.unspotlight",
            "recordings",
            "recordings",
            "unspotlight",
            sensitive,
            owner_service="events",
            owner_method="list",
            owner_argument="recording_id",
        ),
        Capability(
            "assignments.prioritize",
            "extras",
            "my_assignments",
            "prioritize_assignment",
            write,
            owner_service="events",
            owner_method="list",
            owner_argument="id",
            owner_parameter="recording_id",
        ),
        Capability(
            "assignments.deprioritize",
            "extras",
            "my_assignments",
            "deprioritize_assignment",
            write,
            owner_service="events",
            owner_method="list",
            owner_argument="recording_id",
        ),
        Capability(
            "assignments.reorder",
            "extras",
            "my_assignments",
            "reorder_up_next",
            write,
            owner_service="events",
            owner_method="list",
            owner_argument="source_id",
            owner_parameter="recording_id",
        ),
        Capability("assignments.list", "extras", "my_assignments", "get_my_assignments", read),
        Capability("assignments.completed", "extras", "my_assignments", "get_my_completed_assignments", read),
        Capability("assignments.due", "extras", "my_assignments", "get_my_due_assignments", read),
        Capability("drafts.list", "extras", "drafts", "list_my_drafts", read),
        Capability(
            "webhooks.delete",
            "extras",
            "webhooks",
            "delete",
            sensitive,
            owner_service="webhooks",
            owner_method="get",
            owner_argument="webhook_id",
        ),
        Capability(
            "dock_tools.get",
            "extras",
            "tools",
            "get",
            read,
            owner_service="tools",
            owner_method="get",
            owner_argument="tool_id",
        ),
        Capability("dock_tools.create", "extras", "tools", "create", sensitive, "bucket_id"),
        Capability(
            "dock_tools.update",
            "extras",
            "tools",
            "update",
            sensitive,
            owner_service="tools",
            owner_method="get",
            owner_argument="tool_id",
        ),
        Capability(
            "dock_tools.delete",
            "extras",
            "tools",
            "delete",
            sensitive,
            owner_service="tools",
            owner_method="get",
            owner_argument="tool_id",
        ),
        Capability(
            "dock_tools.enable",
            "extras",
            "tools",
            "enable",
            sensitive,
            owner_service="tools",
            owner_method="get",
            owner_argument="tool_id",
        ),
        Capability(
            "dock_tools.disable",
            "extras",
            "tools",
            "disable",
            sensitive,
            owner_service="tools",
            owner_method="get",
            owner_argument="tool_id",
        ),
        Capability(
            "dock_tools.reposition",
            "extras",
            "tools",
            "reposition",
            sensitive,
            owner_service="tools",
            owner_method="get",
            owner_argument="tool_id",
        ),
        Capability(
            "todolists.create",
            "todos",
            "todolists",
            "create",
            write,
            owner_service="todosets",
            owner_method="get",
            owner_argument="todoset_id",
        ),
        Capability(
            "todolists.get",
            "todos",
            "todolists",
            "get",
            read,
            owner_service="todolists",
            owner_method="get",
            owner_argument="id",
        ),
        Capability(
            "todolists.list",
            "todos",
            "todolists",
            "list",
            read,
            owner_service="todosets",
            owner_method="get",
            owner_argument="todoset_id",
        ),
        Capability(
            "todolists.update",
            "todos",
            "todolists",
            "update",
            write,
            owner_service="todolists",
            owner_method="get",
            owner_argument="id",
        ),
        Capability(
            "todolists.reposition",
            "todos",
            "todolists",
            "reposition",
            write,
            owner_service="todolists",
            owner_method="get",
            owner_argument="todolist_id",
            owner_parameter="id",
        ),
        Capability(
            "todolist_groups.list",
            "todos",
            "todolist_groups",
            "list",
            read,
            owner_service="todolists",
            owner_method="get",
            owner_argument="todolist_id",
            owner_parameter="id",
        ),
        Capability(
            "todolist_groups.create",
            "todos",
            "todolist_groups",
            "create",
            write,
            owner_service="todolists",
            owner_method="get",
            owner_argument="todolist_id",
            owner_parameter="id",
        ),
        Capability(
            "todolist_groups.reposition",
            "todos",
            "todolist_groups",
            "reposition",
            write,
            context_arguments=("todolist_id",),
        ),
        Capability(
            "todosets.get",
            "todos",
            "todosets",
            "get",
            read,
            owner_service="todosets",
            owner_method="get",
            owner_argument="todoset_id",
        ),
        # Explicitly model forbidden Adminland work so it cannot be mistaken for unknown support.
        Capability("admin.billing", "admin", "account", "billing", denied),
        Capability("admin.ownership", "admin", "account", "ownership", denied),
        Capability("admin.security", "admin", "account", "security", denied),
        Capability("admin.classification", "admin", "people", "classification", denied),
        Capability("admin.invitation_acceptance", "admin", "people", "accept_invitation", denied),
    )
    registry = CapabilityRegistry(definitions)
    expanded_reads = {
        "client_approvals.list": "bucket_id",
        "client_correspondences.list": "bucket_id",
        "client_replies.list": "bucket_id",
        "message_types.list": "bucket_id",
        "recordings.list": "bucket",
    }
    for operation, project_argument in expanded_reads.items():
        if operation in registry._items:
            continue
        service, method = operation.split(".", 1)
        registry.register(Capability(operation, "extras", service, method, read, project_argument))
    return registry
